# Generated by Django 3.2.5 on 2021-08-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clendario_Academico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendario_label', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='academic_calendar/')),
                ('subido_a', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
