# Generated by Django 3.2.5 on 2021-08-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentas',
            old_name='is_active',
            new_name='es_activo',
        ),
        migrations.RenameField(
            model_name='cuentas',
            old_name='is_admin',
            new_name='es_admin',
        ),
        migrations.RenameField(
            model_name='cuentas',
            old_name='is_superuser',
            new_name='es_superusuario',
        ),
        migrations.RenameField(
            model_name='cuentas',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='cuentas',
            old_name='fullname',
            new_name='nombrecompleto',
        ),
        migrations.RenameField(
            model_name='cuentas',
            old_name='username',
            new_name='nombreusuario',
        ),
        migrations.RenameField(
            model_name='cuentas',
            old_name='phone_number',
            new_name='numero_celular',
        ),
    ]
