# Generated by Django 3.2.5 on 2021-07-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=255, unique=True)),
                ('evento_foto_portada', models.ImageField(upload_to='evento_portada/')),
                ('eventolugar', models.TextField()),
                ('description', models.TextField()),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
            ],
        ),
    ]
